name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:

      # -----------------------------------
      # Checkout Code
      # -----------------------------------

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # -----------------------------------
      # CodeQL
      # -----------------------------------

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: python

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

      # -----------------------------------
      # Gitleaks
      # -----------------------------------

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      # -----------------------------------
      # Build Docker Image
      # -----------------------------------

      - name: Build Docker Image
        run: docker build -t demo-app:latest .

      # -----------------------------------
      # Trivy Scan
      # -----------------------------------

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'demo-app:latest'
          severity: 'HIGH,CRITICAL'
          format: 'table'
          exit-code: '1'
